[package]
name = "battleship_wasm"
version = "0.1.0"
authors = ["Rainer <rainer@software-architects.at>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "^0.2.0", features = [ "serde-serialize" ] }
battleship_game_logic = { path = "../battleship_game_logic" }
serde = { version = "^1.0.0", features = ["derive"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "^0.1.0", optional = true }

[dev-dependencies]
wasm-bindgen-test = "^0.3.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
