@host = http://localhost:8000

###
# @name add_game
POST {{host}}/games
Content-Type: application/json

{
    "player": "Rainer"
}

###
@game_id = {{add_game.response.body.$}}

GET {{host}}/games/{{game_id}}
Accept: application/json

###
@game_id = {{add_game.response.body.$}}

POST {{host}}/games/{{game_id}}/shoot
Accept: application/json
Content-Type: application/json

"B1"
